#!/usr/bin/env python
# -*- coding: utf-8 -*-
#   __                     __  __
#  /__)  /  /  /\ /  /\ / /_  /__)
# / (   /__/  / \/  / \/ /_  / (
#         

"""
tizen stability test runner to wrap testkit-lite.
usage:
      strunner -h

dependency python library: jinja2
As of version 2.7 Jinja2 depends on the MarkupSafe module.
If you install Jinja2 via pip or easy_install it will be installed
automatically for you.
sudo easy_install jinja2
sudo pip install jinja2

copyright: see LICENSE for more details.
license: see LICENSE for more details.
"""

__title__ = 'strunner'
__version__ = '1.0'
__author__ = 'hongbinx.bao@intel.com'
__date__ = '12-31-2013'

import sys
from stabilityrunner import option, testrunner

testrunner(option=option(sys.argv), engine='testkit-lite').run()

